on:
  pull_request:
    branches:
      - dev
   
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      -  uses: actions/checkout@v2
      -  run: npm install sfdx-cli -g
      -  run: echo "${{ secrets.SALESFORCE_SERVER_KEY }}" > server.key
        
      -  name: 'Salesforce Dev Environment Authentication' 
         run:  sfdx force:auth:jwt:grant --clientid=${{ secrets.SALESFORCE_CONSUMER_KEY }} --jwtkeyfile=server.key --username=${{ secrets.SALESFORCE_USERNAME }} --setdefaultdevhubusername
     
      -  name: 'Salesforce Dev Environment Metadata Validation' 
         run:  sfdx force:source:deploy -x manifest/package.xml --checkonly -u ${{ secrets.SALESFORCE_USERNAME }}
