on:
  pull_request:
    branches: [ main ]
    types:
      - closed
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -  uses: actions/checkout@v2
      -  run: npm install sfdx-cli -g
      -  run: echo "${{ secrets.SALESFORCE_SERVER_KEY }}" > server.key
        
      -  name: 'Salesforce Org Authentication' 
         run:  sfdx force:auth:jwt:grant --clientid=${{ secrets.SALESFORCE_CONSUMER_KEY }} --jwtkeyfile=server.key --username=${{ secrets.SALESFORCE_USERNAME }} --setdefaultdevhubusername
     
      -  name: 'Salesforce Org Metadata Validation' 
         run:  sfdx force:source:deploy -x manifest/package.xml --check-only -u ${{ secrets.SALESFORCE_USERNAME }}
