on:
  pull_request:
    branches:
      - main
   
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     
      -  name: 'Salesforce Production Environment Authentication' 
         if: github.event_name == 'pull_request' 
         run:  sfdx force:auth:jwt:grant --clientid=${{ secrets.SALESFORCE_CONSUMER_KEY_PROD }} --jwtkeyfile=server.key --username=${{ secrets.SALESFORCE_USERNAME_PROD }} --setdefaultdevhubusername
     
      -  name: 'Salesforce Org Metadata Validation for Production' 
         if: github.event_name == 'pull_request' 
         run:  sfdx force:source:deploy -x manifest/package.xml --checkonly -u ${{ secrets.SALESFORCE_USERNAME_PROD }}

      -  name: 'Salesforce Org Metadata Deployment to Production' 
         if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
         run:  sfdx force:source:deploy -x manifest/package.xml -u ${{ secrets.SALESFORCE_USERNAME_PROD }}