on:
  pull_request:
    branches: [ main ]
    types:
      - closed
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -  uses: actions/checkout@v2
      -  run: npm install sfdx-cli -g
      -  run: echo "${{ secrets.SALESFORCE_SERVER_KEY }}" > server.key
        
      -  name: 'Salesforce Org Authentication' 
         run:  |
         source ~/.bashrc
         sf org login jwt --clientid=${{ secrets.SALESFORCE_CONSUMER_KEY }} --username=${{ secrets.SALESFORCE_USERNAME }} --jwtkeyfile=server.key --instanceurl https://login.salesforce.com
     
     
