on:
  pull_request:
    branches:
      - staging
          
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -  uses: actions/checkout@v2
      -  run: npm install sfdx-cli -g
      -  run: echo "${{ secrets.SALESFORCE_SERVER_KEY }}" > server.key
        
      -  name: 'Salesforce Staging Environment Authentication' 
         run:  sfdx force:auth:jwt:grant --clientid=${{ secrets.SALESFORCE_CONSUMER_KEY_STAGE }} --jwtkeyfile=server.key --username=${{ secrets.SALESFORCE_USERNAME_STAGE }} --setdefaultdevhubusername
     
      -  name: 'Salesforce Org Metadata Validation for Staging' 
         run:  sfdx force:source:deploy -x manifest/package.xml --checkonly -u ${{ secrets.SALESFORCE_USERNAME_STAGE }}

    
      
