on:
  pull_request:
    branches:
      - staging
    types:
      - closed
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -  uses: actions/checkout@v2
      -  run: npm install sfdx-cli -g
      -  run: echo "${{ secrets.SALESFORCE_SERVER_KEY }}" > server.key
        
      -  name: 'Salesforce Staging Environment Authentication' 
         if: github.event_name == 'pull_request'
         run:  sfdx force:auth:jwt:grant --clientid=${{ secrets.SALESFORCE_CONSUMER_KEY_STAGE }} --jwtkeyfile=server.key --username=${{ secrets.SALESFORCE_USERNAME_STAGE }} --setdefaultdevhubusername
     
      -  name: 'Salesforce Org Metadata Validation for Staging' 
         if: github.event_name == 'pull_request'
         run:  sfdx force:source:deploy -x manifest/package.xml --checkonly -u ${{ secrets.SALESFORCE_USERNAME_STAGE }}

      -  name: 'Salesforce Org Metadata Deployment to Staging' 
         if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true 
         run:  sfdx force:source:deploy -x manifest/package.xml -u ${{ secrets.SALESFORCE_USERNAME_STAGE }}

      
